import { getTranslations } from "next-intl/server";

import { Link } from "@/i18n/navigation";
import { FEED_TABS, type FeedTab } from "@/lib/feed-types";
import { cn } from "@/lib/utils";

export type FeedTabsProps = {
  tab: FeedTab;
};

/**
 * `following`/`popular` tabs for `/feed` (FE-23), same shape as `StatusTabs`/
 * `TypeTabs` in `/u/{username}/library`'s page: plain server-rendered `Link`s
 * (works with JS disabled, crawlable) driven entirely by the `tab` query
 * param — no client-side state, so an invalid `tab` is simply never
 * generated by this UI (only {@link FEED_TABS}' two values ever appear in a
 * link's `href`), satisfying FE-23's "an invalid tab must not be reachable
 * from the UI" acceptance criterion.
 */
export async function FeedTabs({ tab }: FeedTabsProps) {
  const t = await getTranslations("Feed.tabs");

  function hrefFor(target: FeedTab) {
    const query: Record<string, string> = {};
    if (target !== "following") {
      query.tab = target;
    }
    return { pathname: "/feed", query };
  }

  return (
    <div role="tablist" aria-label={t("label")} className="flex flex-wrap gap-2">
      {FEED_TABS.map((value) => {
        const isActive = value === tab;
        return (
          <Link
            key={value}
            href={hrefFor(value)}
            role="tab"
            aria-selected={isActive}
            className={cn(
              "rounded-full border px-3 py-1 text-sm font-medium transition-colors",
              isActive
                ? "border-transparent bg-primary text-primary-foreground"
                : "border-border bg-background text-muted-foreground hover:text-foreground",
            )}
          >
            {t(value)}
          </Link>
        );
      })}
    </div>
  );
}
