import type { Metadata } from "next";
import { getTranslations, setRequestLocale } from "next-intl/server";
import Image from "next/image";
import { notFound } from "next/navigation";

import { CatalogCard } from "@/components/catalog-card";
import { FollowWidget } from "@/components/follow-widget";
import { LibraryStatusCounts } from "@/components/library-status-counts";
import { ProfileReviewsPagination } from "@/components/profile-reviews-pagination";
import { buttonVariants } from "@/components/ui/button";
import { UserReviewCard } from "@/components/user-review-card";
import { Link } from "@/i18n/navigation";
import { getCurrentUser } from "@/lib/api-fetch";
import { getUserLibrary, getUserProfile, type LibraryEntry, type UserProfile } from "@/lib/library";
import { toCatalogType } from "@/lib/search";
import { getUserReviews } from "@/lib/user-content";
import { cn } from "@/lib/utils";

/** Page size for the reviews section — matches `PAGE_LIMIT` in `item-reviews.tsx`. */
const REVIEWS_PAGE_SIZE = 10;

/**
 * Item count for the library preview grid on this page — a taste, not the
 * full listing that `/u/{username}/library` (FE-20) already owns. Six items
 * fill exactly one row of the `lg:grid-cols-6` layout below.
 */
const LIBRARY_PREVIEW_SIZE = 6;

type RawParam = string | string[] | undefined;

function firstValue(value: RawParam): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

function parsePage(value: RawParam): number {
  const raw = firstValue(value);
  const parsed = raw ? Number.parseInt(raw, 10) : 1;
  return Number.isInteger(parsed) && parsed >= 1 ? parsed : 1;
}

type ProfileTranslator = Awaited<ReturnType<typeof getTranslations<"Profile">>>;
type BrowseTranslator = Awaited<ReturnType<typeof getTranslations<"Browse">>>;

/**
 * OG metadata for the public profile page (FE-45). Same `{}`-on-non-`ok`
 * degrade as `[type]/[slug]/page.tsx`'s `generateMetadata` (falls back to the
 * root layout's `Metadata.home` title/description) — a genuine 404 username
 * and a transient fetch failure are handled identically here since metadata
 * doesn't need the page's `notFound()` vs. inline-error distinction.
 *
 * `openGraph.images` uses the user's `avatar_url` when set, otherwise falls
 * back to the generic branded image generated by `app/opengraph-image.tsx`
 * (referenced explicitly here — `generateMetadata` already overrides
 * `openGraph` wholesale, so Next's own file-convention auto-wiring wouldn't
 * apply once this object is returned). The relative `/opengraph-image` path
 * resolves to an absolute URL via `metadataBase` (`[locale]/layout.tsx`),
 * which crawlers require.
 */
export async function generateMetadata({
  params,
}: PageProps<"/[locale]/u/[username]">): Promise<Metadata> {
  const { locale, username } = await params;
  const result = await getUserProfile(username);
  if (result.status !== "ok") {
    return {};
  }

  const profile = result.profile;
  const name = profile.display_name ?? profile.username;
  const tm = await getTranslations({ locale, namespace: "Metadata.profile" });
  const title = tm("title", { name });
  const description = profile.bio ?? tm("descriptionFallback", { name });

  return {
    title,
    description,
    // Autocanonical (FE-53): this page has no query params to strip (unlike
    // `browse/[type]`), but still needs an explicit canonical — without one,
    // the same profile would be indexable per-locale with no declared
    // preferred URL.
    alternates: { canonical: `/${locale}/u/${username}` },
    openGraph: {
      title,
      description,
      type: "website",
      images: [profile.avatar_url ?? "/opengraph-image"],
    },
  };
}

/**
 * Public profile page for one user (FE-21), `/u/{username}` — the full
 * profile that `/u/{username}/library` (FE-20) and `item-reviews.tsx`'s
 * author link both already reference. Loads the profile (`getUserProfile`),
 * this page's own reviews (`getUserReviews`, paginated via the `page` query
 * param) and a small library preview (`getUserLibrary`, capped at
 * `LIBRARY_PREVIEW_SIZE`) in parallel, plus the caller's own session
 * (`getCurrentUser`) to tell own vs. someone else's profile apart.
 *
 * Only a backend-confirmed 404 username goes through `notFound()` — same
 * `not-found`/`error` split as `getItemDetail`'s doc comment
 * (`src/lib/catalog.ts`) and the sibling library page. Reviews/library
 * failures degrade to their own inline error states (or, for the library
 * preview, silently fall back to the counts-only summary) instead of failing
 * the whole page, since the profile header itself is still valid and worth
 * showing.
 */
export default async function UserProfilePage({
  params,
  searchParams,
}: PageProps<"/[locale]/u/[username]">) {
  const { locale, username } = await params;
  setRequestLocale(locale);

  const query = await searchParams;
  const page = parsePage(query.page);

  const [t, tType, profileResult, reviewsResult, libraryResult, currentUser] = await Promise.all([
    getTranslations("Profile"),
    getTranslations("Browse"),
    getUserProfile(username),
    getUserReviews(username, { page, limit: REVIEWS_PAGE_SIZE }),
    getUserLibrary(username, { limit: LIBRARY_PREVIEW_SIZE }),
    getCurrentUser(),
  ]);

  if (profileResult.status === "not-found") {
    notFound();
  }

  if (profileResult.status === "error") {
    return (
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-4 px-6 py-16">
        <p role="alert" className="text-sm text-destructive">
          {t("error")}
        </p>
      </div>
    );
  }

  const profile = profileResult.profile;
  const isOwnProfile = currentUser?.username === username;
  const totalReviewPages = reviewsResult.ok
    ? Math.max(1, Math.ceil(reviewsResult.total / reviewsResult.limit))
    : 1;

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-10 px-6 py-16">
      <ProfileHeader profile={profile} isOwnProfile={isOwnProfile} t={t} />

      <LibrarySummary
        username={username}
        counts={profile.library_counts}
        preview={libraryResult.ok ? libraryResult.items : []}
        t={t}
        tType={tType}
      />

      <section className="flex flex-col gap-4">
        <h2 className="text-xl font-medium">{t("reviews.heading")}</h2>
        {!reviewsResult.ok ? (
          <p role="alert" className="text-sm text-destructive">
            {t("reviews.error")}
          </p>
        ) : reviewsResult.items.length === 0 ? (
          <p className="text-sm text-muted-foreground">{t("reviews.empty")}</p>
        ) : (
          <>
            <div className="flex flex-col gap-4">
              {reviewsResult.items.map((review) => (
                <UserReviewCard
                  key={review.id}
                  review={review}
                  locale={locale}
                  dateLabel={(date) => t("reviews.dateLabel", { date })}
                />
              ))}
            </div>
            <ProfileReviewsPagination username={username} page={page} totalPages={totalReviewPages} />
          </>
        )}
      </section>
    </div>
  );
}

function ProfileHeader({
  profile,
  isOwnProfile,
  t,
}: {
  profile: UserProfile;
  isOwnProfile: boolean;
  t: ProfileTranslator;
}) {
  const name = profile.display_name ?? profile.username;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex items-center gap-4">
          {profile.avatar_url ? (
            <Image
              src={profile.avatar_url}
              alt=""
              width={64}
              height={64}
              className="size-16 rounded-full object-cover"
            />
          ) : (
            <span
              aria-hidden="true"
              className="flex size-16 items-center justify-center rounded-full bg-muted text-lg font-medium"
            >
              {name.slice(0, 2).toUpperCase()}
            </span>
          )}
          <div className="flex flex-col gap-1">
            <h1 className="text-2xl font-semibold tracking-tight">{name}</h1>
            <p className="text-sm text-muted-foreground">@{profile.username}</p>
          </div>
        </div>

        {isOwnProfile ? (
          <Link href="/settings" className={cn(buttonVariants({ variant: "outline" }))}>
            {t("editProfileLink")}
          </Link>
        ) : null}
      </div>

      {profile.bio ? <p className="max-w-2xl text-sm leading-6 text-foreground">{profile.bio}</p> : null}

      <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
        <FollowWidget
          username={profile.username}
          initialFollowerCount={profile.follower_count}
          isOwnProfile={isOwnProfile}
        />
        <Link href={`/u/${profile.username}/following`} className="hover:text-foreground hover:underline">
          {t("followingCount", { count: profile.following_count })}
        </Link>
      </div>
    </div>
  );
}

/**
 * Library section of the profile (FE-21, enriched post-QA; counts made
 * prominent in FE-39): a colored per-status count summary
 * (`LibraryStatusCounts`, FE-39) is the at-a-glance headline, paired with a
 * small poster preview (`CatalogCard`, same component the full library grid
 * at `/u/{username}/library` uses) of the user's `LIBRARY_PREVIEW_SIZE` most
 * recent entries — the preview is simply omitted when `preview` is empty (no
 * empty-state copy), same as how the full library page treats a genuinely
 * empty library.
 */
function LibrarySummary({
  username,
  counts,
  preview,
  t,
  tType,
}: {
  username: string;
  counts: UserProfile["library_counts"];
  preview: LibraryEntry[];
  t: ProfileTranslator;
  tType: BrowseTranslator;
}) {
  return (
    <section className="flex flex-col gap-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-xl font-medium">{t("library.heading")}</h2>
        <Link href={`/u/${username}/library`} className="text-sm font-medium text-primary hover:underline">
          {t("library.viewAll")}
        </Link>
      </div>
      <LibraryStatusCounts username={username} counts={counts} />
      {preview.length > 0 ? (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
          {preview.map((entry) => {
            const itemType = toCatalogType(entry.item.item_type);
            return (
              <CatalogCard
                key={`${entry.item.item_type}-${entry.item.slug}`}
                title={entry.item.title}
                posterUrl={entry.item.poster_url}
                ratingInternal={entry.item.rating_internal}
                typeLabel={itemType ? tType(`heading.${itemType}`) : entry.item.item_type}
                href={itemType ? `/${itemType}/${entry.item.slug}` : undefined}
              />
            );
          })}
        </div>
      ) : null}
    </section>
  );
}

